sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t helencalhoun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true helencalhoun/react-test npm test

after_success:
  - docker build -t helencalhoun/multi-client ./client
  - docker build -t helencalhoun/multi-nginx ./nginx
  - docker build -t helencalhoun/multi-server ./server
  - docker build -t helencalhoun/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push helencalhoun/multi-client
  - docker push helencalhoun/multi-nginx
  - docker push helencalhoun/multi-server
  - docker push helencalhoun/multi-worker

deploy:
	provider: elasticbeanstalk
	region: 'us-east-1'
	app: 'multi-docker'
	env: 'Multidocker-env'
	bucket_name: elasticbeanstalk-us-east-1-857207154436
	bucket_path: 'docker-multi'
	on:
		branch: master
	access_key_id: $AWS_ACCESS_KEY
	secret_access_key: $AWS_SECRET_KEY